name = "pomometer"
type = "webpack"
account_id = "17ad48740eef0cc8f607145995815f37"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "/github/workspace/build",entry-point = "workers-site"}
